main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name="signup"),
    path('account_settings/', views.account_settings, name="account_settings"),
    path("product/<int:prod_id>", views.productView, name="ProductView"),
    path('contact/', views.contact, name="contact"),
    path("products/<str:catg>", views.view_all, name="products_view_all"),
    path('plus_element_cart/', views.plus_element_cart),
    path('minus_element_cart/', views.minus_element_cart),
    path('add_to_cart/', views.add_to_cart),
    path('delete_from_cart/', views.delete_from_cart),
    path('dummy_cart/', views.dummy_cart),
    path('cart/', views.cart, name="main_cart"),
    path('checkout/', views.checkout, name="main_checkout"),
    path('order_now/', views.order_now, name="order_now"),
    path('myorders/', views.MyOrders, name="myorders"),
    path('search/', views.search, name="search"),
    path('MenuFilter/<str:querys>', views.MenuFilter, name="MenuFilter"),
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    path("about/", views.about, name='about'),
    path("term/", views.term, name='term'),
  
  
  
    ]

wrappers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from saler.views import admin2

urlpatterns = [
    path('wrappers/india/my/admin/pannel/home/', admin.site.urls),
    path('wrappers/india/my/admin/pannel/admin20/', admin2, name = 'admin2'),
    path('', include('main.urls')),
    path('seller/', include('saler.urls')),
    path("login/", auth_views.LoginView.as_view(template_name='main/login.html', redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'), name="password_reset_complete"),
    path("coupon/",include('coupon.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import UserDetail

class UserRegisterForm(UserCreationForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={}))
	gst = forms.CharField(label=("GST Number"),widget=forms.TextInput(attrs={}))
	username = forms.CharField(label=("Mobile Number/Email"),widget=forms.TextInput(attrs={'oninput':'validate()'}))
	password1 = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={}),)
	password2  = forms.CharField(label=("Confirm"), strip=False, widget=forms.PasswordInput(attrs={}),)
	class Meta:
		model = User
		fields = ['first_name', 'last_name','gst', 'username', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = [
			'first_name',
			 'last_name',
			 'email',
		]

class UpdateUserDetailForm(forms.ModelForm):
	class Meta:
		model = UserDetail
		fields = [
			'dob',
			'photo',
			'mobile',
			'alternate_mobile',
			'address',
			'pincode',
			'landmark',
			'locality',
			'city',
			'state',
			'sex',
		]

class UserAddressForm1(forms.ModelForm):
	class Meta:
		model = User
		fields = [
			'first_name',
			 'last_name',
		]
class UserAddressForm(forms.ModelForm):
	address = forms.CharField(widget=forms.TextInput(attrs={}))
	locality = forms.CharField(required =True)
	city = forms.CharField(required =True)
	alternate_mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Alternate Mobile No(optional)'}), required = False)
	landmark = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Landmark(optional)'}), required = False)
	class Meta:
		model = UserDetail
		fields = [
			'mobile',
			'alternate_mobile',
			'address',
			'pincode',
			'landmark',
			'locality',
			'city',
			'state',
		]

main/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UpdateUserDetailForm, UserUpdateForm, UserAddressForm, UserAddressForm1
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.models import User
from .models import UserDetail, Slider, Contact, Cart
from django.contrib.auth.decorators import login_required
from saler.models import Product, ProductSize, dow, category, Orders, trend, ProductReview
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.views.decorators.csrf import csrf_exempt
from .PayTm import Checksum

def index(request):
	if request.user.is_superuser:
		return redirect('admin2')
	elif request.user.is_staff:
		return redirect("saler_home")
	else:
		pass

	prod = Product.objects.all()
	allProds = []
	catprods = Product.objects.values('category', 'product_id')
	cats = {item['category'] for item in catprods}
	for cat in cats:
		prod = []
		for p in [i for i in Product.objects.filter(category=cat)]:
			prod.append([p,[item for item in ProductSize.objects.filter(product=p)]])
		n = len(prod)
		nSlides = 5
		allProds.append([prod[::-1], range(1, nSlides), nSlides])
	params = {
		'sliders':Slider.objects.all(),
		'allProds':allProds,
		'category':category.objects.all(),
		#'prod_men' : [i for i in prod if i.buyer_gender == 'Male'],
		#'prod_women' : [i for i in prod if i.buyer_gender == 'Female'],
		#'prod_other' : [i for i in prod if i.buyer_gender == 'All'],
		'dow' : dow.objects.all()[0:30],
		'trend': trend.objects.order_by('-number')[0:30],
		'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
	}
	return render(request, 'main/index.html', params)

def register(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			form = UserRegisterForm(request.POST)
			if form.is_valid():
				form.save();
				gst = form.cleaned_data.get('gst')
				username = form.cleaned_data.get('username')
				usr = User.objects.filter(username=username).first()
				if username.isdigit():
					UserDetail(user=usr,mobile=username,gst_Number=gst).save()
				else:
					usr.email = username
					usr.save()
					UserDetail(user=usr,gst_Number=gst).save()
				messages.success(request, f'Account is Created for {username}')
				return redirect('login')
		else:
			form = UserRegisterForm()
	return render(request, 'main/signup.html', {'form':form, 'title':'Sign Up','category':category.objects.all()})

@login_required
def account_settings(request):
	if request.method == 'POST':
		#User Details Update
		s_form = UpdateUserDetailForm(request.POST, request.FILES, instance=request.user.userdetail)
		u_form = UserUpdateForm(request.POST, instance=request.user)
		if s_form.is_valid() and u_form.is_valid():
			s_form.save()
			u_form.save()
			messages.success(request, f'Your Account has been Updated!')
			return redirect("account_settings")

		#Change Password
		pass_change_form = PasswordChangeForm(request.user, request.POST)
		if pass_change_form.is_valid():
			user = pass_change_form.save()
			update_session_auth_hash(request, user)  # Important!
			messages.success(request, 'Your password was successfully updated!')
			return redirect('account_settings')
		else:
			messages.error(request, 'Please correct the error below.')

	else:
		s_form = UpdateUserDetailForm(instance=request.user.userdetail)
		u_form = UserUpdateForm(instance=request.user)
		pass_change_form = PasswordChangeForm(request.user)
	detl = {
		'u_form':u_form,
		's_form':s_form,
		'pass_change_form':pass_change_form,
		'title':'User Account Settings',
		'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
		'category':category.objects.all(),
		}
	return render(request, 'main/account_settings.html', detl)

def productView(request, prod_id):
	if request.method == 'POST' and request.user.is_authenticated:
		prod = Product.objects.filter(product_id = prod_id).first()
		review = request.POST.get('review')
		ProductReview(user=request.user,product=prod,review=review).save()
		return redirect(f"/product/{prod_id}")

	prod = Product.objects.filter(product_id = prod_id).first()
	params = {
		'product':prod,
		'product_review': ProductReview.objects.filter(product = prod),
		'sizes':[item for item in ProductSize.objects.filter(product=Product.objects.filter(product_id = prod_id)[0])],
		'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
		'category':category.objects.all(),
	}
	return render(request, 'main/single.html', params)


def view_all(request, catg):
	if catg=='dow':
		params = {
			'product':[i for i in dow.objects.all()][::-1],
			'catg':'Deal of the Week',
			'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
			'category':category.objects.all(),
			}
		return render(request, 'main/view_dow.html', params)
	elif catg=='trend':
		prod = []
		for p in trend.objects.order_by('number'):
			prod.append([p.product,[item for item in ProductSize.objects.filter(product=p.product)]])
		params = {
			'product':prod,
			'catg':'Treanding',
			'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
			'category':category.objects.all(),
			}
		return render(request, 'main/view_all.html', params)
	else:
		prod = []
		for p in [i for i in Product.objects.all() if str(i.category) == catg]:
			prod.append([p,[item for item in ProductSize.objects.filter(product=p)]])
		params = {
			'product':prod,
			'catg':catg,
			'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
			'category':category.objects.all(),
			}
	return render(request, 'main/view_all.html', params)


def search(request):
	query = request.GET.get('query', '')
	prods = []
	for prod in [i for i in Product.objects.all() ]:
		if query.lower() in prod.product_name.lower() or query.lower() in prod.desc.lower() or query.lower() in prod.subcategory.lower():
			prods.append([prod,[item for item in ProductSize.objects.filter(product=prod)]])
	params = {
		'product':prods,
		'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
		'category':category.objects.all(),
		}
	return render(request, 'main/view_all.html', params)

cart_item_local = []

def dummy_cart(request):
	if request.method == 'GET':
		prod_list = request.GET['prod_list']
		prod_list = prod_list.split(',')
		if request.user.is_authenticated:
			cart_prods = [p for p in Cart.objects.all() if p.user == request.user]
			card_prods_id =[i.product_id for i in cart_prods]
			if len(prod_list) >= 1 and prod_list != ['']:
				for item in prod_list:
					pppp = item.split('|')
					if pppp[0] in card_prods_id:
						cart_prods[card_prods_id.index(pppp[0])].number = int(pppp[1])
						cart_prods[card_prods_id.index(pppp[0])].save()
					else:
						Cart(user = request.user, product_id = pppp[0], number = int(pppp[1])).save()
		else:
			global cart_item_local
			cart_item_local = prod_list
	return HttpResponse("data sebd from py")

@login_required
def cart(request):
	if request.user.is_authenticated:
		allProds = []
		subtotal = 0.0
		delev = 0.0
		tax = 0.0
		cart_prods = [p for p in Cart.objects.all() if p.user == request.user]
		for p in cart_prods:
			tempTotal = p.number * Product.objects.filter(product_id=p.product_id)[0].price
			subtotal += tempTotal
			tax += tempTotal*int(Product.objects.filter(product_id=p.product_id).first().gst)/100

		for cprod in cart_prods:
			prod = Product.objects.filter(product_id=cprod.product_id)[0]
			allProds.append([cprod, prod])
		params = {
					'allProds':allProds,
					'cart_element_no' : len([p for p in Cart.objects.all() if p.user == request.user]),
					'total':subtotal+tax+delev,
					'subtotal':subtotal,
					'tax':tax,
					'delev':delev,
					'category':category.objects.all(),
				}
		return render(request,'main/cart.html', params)

@login_required
def add_to_cart(request):
	cart_prods = [p for p in Cart.objects.all() if p.user == request.user]
	card_prods_id =[i.product_id for i in cart_prods]
	if request.method == 'GET':
		prod_id = request.GET['prod_id']
		prod_id = prod_id.split(',')
		for item in cart_prods:
			if prod_id[0] == item.product_id and prod_id[1] == item.product_size:
				item.number += 1
				item.save()
				return HttpResponse(len(cart_prods))
		Cart(user = request.user, product_id = int(prod_id[0]),product_size=prod_id[1], number = 1).save()
		return HttpResponse(len(cart_prods)+1)
	else:
		return HttpResponse("")

@login_required
def plus_element_cart(request):
	if request.method == 'GET':
		prod_id = request.GET['prod_id']
		c = Cart.objects.get(id=prod_id)
		c.number+=1
		c.save()
		subtotal = 0.0
		delev = 0.0
		tax = 0.0
		cart_prods2 = [p for p in Cart.objects.all() if p.user == request.user]
		for p in cart_prods2:
			tempTotal = p.number * Product.objects.filter(product_id=p.product_id)[0].price
			subtotal += tempTotal
			tax += tempTotal*int(Product.objects.filter(product_id=p.product_id).first().gst)/100

		datas = {
			'num':Cart.objects.get(id=prod_id).number,
			'tax':tax,
			'subtotal':subtotal,
			'delev' : delev,
			'total':subtotal+tax+delev,
			}
		return JsonResponse(datas)
	else:
		return HttpResponse("")

@login_required
def minus_element_cart(request):
	if request.method == 'GET':
		prod_id = request.GET['prod_id']
		c = Cart.objects.get(id=prod_id)
		c.number-=1
		c.save()
		subtotal = 0.0
		delev = 0.0
		tax = 0.0
		cart_prods2 = [p for p in Cart.objects.all() if p.user == request.user]
		for p in cart_prods2:
			tempTotal = p.number * Product.objects.filter(product_id=p.product_id)[0].price
			subtotal += tempTotal
			tax += tempTotal*int(Product.objects.filter(product_id=p.product_id).first().gst)/100

		datas = {
			'num':Cart.objects.get(id=prod_id).number,
			'tax':tax,
			'subtotal':subtotal,
			'delev' : delev,
			'total':subtotal+tax+delev,
			}

main/templates/main/cart.html
{% extends 'main/base.html' %}
{% load static %}
{% block main_head %}
<title>{{request.user.first_name}} Cart</title>
<style type="text/css">


  .prodnamicat {
    display: inline;
  }
</style>



{% endblock main_head %}
{% block main_body %}




<div class="columns is-vcentered">
  <div class="column is-8 px-2">
    <p class="mt-2 text-l -8 font-bold tracking-tight text-gray-700 sm:text-xl px-4 tag is-link is-light">My Cart ({{cart_element_no}})</p>
    <div class="px-4">
    <div class="box">
      {% for cprod, prod in allProds %}
      <div class="columns">
        <div class="column is-two-fifths">
 
  <span class="w3-hide-small">         <img src="{{prod.image1.url}}" class="card-img" alt="..."
          style="max-height: 160px; width: auto; max-width: 80%">
  </span>       
   
<span class="w3-hide-large">         <img src="{{prod.image1.url}}" class="card-img" alt="..."
    style="max-height: 160px;  max-width: 100%">
</span> 
        </div>
        <div class="column">
          <p class="font-bold tracking-tight text-gray-900 py-2">{{prod.product_name}}</p>
          <p class=" tracking-tight text-gray-600 px-2">Category: {{prod.category}}</p>
          <p class="card-text px-2 py-2"><i class="fa fa-plus-square plus_prod" product_id={{cprod.id}}
            aria-hidden="true"></i> <strong>{{cprod.number}}</strong> <i
            class="fa fa-minus-square minus_prod" aria-hidden="true" product_id={{cprod.id}}></i></p>
          <p class="card-text px-2 py-3 text-2xl"><strong><i class="fa fa-inr" aria-hidden="true"></i>{{prod.price}}</strong></p>
        </div>
        <div class="column">
          <p class="card-text py-8 w3-hide-small"><b>Size :- </b>
            {{cprod.product_size}}
          </p>
          <p class="card-text w3-hide-large"><b>Size :- </b>
            {{cprod.product_size}}
          </p>
          <a class="btn btn-danger text-dark delete" product_id={{cprod.id}}
          style=" color: rgb(30, 18, 196);"></a>
        </div>
      </div>
      {% endfor %}
    </div>
    </div>
  </div>
 



  <div class="column">
    <div classs="py-2">
    <span class="tag is-success is-light">Order summary 
      {% if not request.user.is_authenticated  %}
      <a style="float: right;" href="">Refresh</a>
      {% endif %}</span><br>
     </div>
      <div class="box">
        <ul class="list-unstyled mb-4">
          <li class="d-flex justify-content-between py-3 border-bottom"> Order Subtotal 
            <strong id="subtotal"><i class="fa fa-inr" aria-hidden="true"></i>{{subtotal}}</strong></li>
          <li class="d-flex justify-content-between py-3 border-bottom">
              handling<strong id="delev"><i class="fa fa-inr" aria-hidden="true"></i>{{delev}}</strong></li>
          <li class="d-flex justify-content-between py-3 border-bottom">Tax<strong
              id="tax"><i class="fa fa-inr" aria-hidden="true"></i>{{tax}}</strong></li>
          <li class="d-flex justify-content-between py-3 border-bottom">Total
            <h5 class="font-weight-bold" id="total"><i class="fa fa-inr" aria-hidden="true"></i>{{total}}</h5>
          </li>
        </ul><a href="{% url 'main_checkout' %}" class="button is-dark rounded-pill py-2 btn-block">Procceed to
          checkout</a>
    </div>
  </div>
</div>

<!--smallscreen-->



{% endblock main_body %}

{% block main_script %}
<!-- Js For Delete Element -->
<script type="text/javascript">
  $('.delete').click(function () {
    var catid = $(this).attr("product_id").toString();
    var elm = this;
    $.ajax(
      {
        type: "GET",
        url: "/delete_from_cart",
        data: {
          prod_id: catid
        },
        success: function (data) {
          $('#cart_no').text(data.len);
          document.getElementById('subtotal').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.subtotal}`;
          document.getElementById('total').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.total}`;
          document.getElementById('tax').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.tax}`;
          document.getElementById('delev').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.delev}`;
          elm.parentNode.parentNode.parentNode.parentNode.parentNode.remove()

        }
      })
  });

</script>
<!-- Js For Increase Element -->

<script type="text/javascript">
  $('.plus_prod').click(function () {
    var id = $(this).attr("product_id").toString();
    var eml = this.parentNode.children[1];

    $.ajax(
      {
        type: "GET",
        url: "/plus_element_cart",
        data: {
          prod_id: id
        },
        success: function (data) {
          eml.innerText = data.num;
          document.getElementById('subtotal').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.subtotal}`;
          document.getElementById('total').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.total}`;
          document.getElementById('tax').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.tax}`;
          document.getElementById('delev').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.delev}`;
        }
      })
  });
</script>

<!-- Js For Decrease Element -->

<script type="text/javascript">
  $('.minus_prod').click(function () {
    var catid = $(this).attr("product_id").toString();
    var eml = this.parentNode.children[1];
    $.ajax(
      {
        type: "GET",
        url: "/minus_element_cart",
        data: {
          prod_id: catid
        },
        success: function (data) {
          eml.innerText = data.num;
          document.getElementById('subtotal').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.subtotal}`;
          document.getElementById('total').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.total}`;
          document.getElementById('tax').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.tax}`;
          document.getElementById('delev').innerHTML = `<i class="fa fa-inr" aria-hidden="true"></i>${data.delev}`;
        }
      })
  });
</script>
{% endblock main_script %}

main/templates/main/password_reset.html
{% extends 'main/account_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_account %}
<form method="POST" class="signup_form mr-2 ml-2">
	{% csrf_token %}
	<fieldset>
		{{form|crispy}}
	</fieldset>
	<section class="mt-4 mr-1 ml-1">
		<input type="submit" class="btn btn-primary m-0" value="Request Password Reset" style="background-color: #231f20; border:0;">
	</section>
	<div class="subtitle pt-2 mt-1"></div>
</form>
{% endblock body_account %}

main/templates/main/password_reset_confirm.html
{% extends 'main/account_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_account %}
<form method="POST" class="signup_form mr-2 ml-2">
	{% csrf_token %}
	<fieldset>
		{{form|crispy}}
	</fieldset>
	<section class="mt-4 mr-1 ml-1">
		<input type="submit" class="btn btn-primary m-0" value="Reset Password" style="background-color: #231f20; border:0;">
	</section>
	<div class="subtitle pt-2 mt-1"></div>
</form>
{% endblock body_account %}

main/templates/main/paymentstatus.html
{% extends 'main/base.html' %}
{% block main_body %}
<div class="container">
    {{response}}
    <div class="col my-4">

        <h2>Payment status regarding your order Id {{response.ORDERID}}</h2>
        {% if response.RESPCODE == '01' %}
        ORDER SUCCESS
        {% else %}
        ORDER FAILURE
        {% endif%}

    </div>

</div>
{% endblock main_body %}

main/templates/main/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm merchant payment page</title>
</head>
<body>
<h1>Redirecting you to the merchant....</h1>
<h1>Please do not refresh your page....</h1>
<form action="https://securegw.paytm.in/order/process" method="post" name="paytm">
    {% for key, value in param_dict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
    {% endfor %}

</form>
</body>
<script>
document.paytm.submit()
</script>
</html>

main/templates/main/signup.html
{% extends 'main/account_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_account %}
<style type="text/css">
  input {
    display: none;
  }
</style>
<div class="columns w3-hide-small">
  <div class="column">
    <form method="POST" class="signup_form mr-4 ml-4">
      {% csrf_token %}
      <fieldset>
        <h1 class="py-2 text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
          <span class="block xl:inline">Create</span>
          <span class="block text-orange-600 xl:inline">Account</span>
        </h1>
        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
            {{ form.first_name | as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.last_name | as_crispy_field }}
          </div>
        </div>
        {{ form.username| as_crispy_field }}
        <p id="error_1_id_username" class="invalid-feedback" style="display: inline-block;">
          <strong id="usrerr"></strong>
        </p>

        {{ form.gst| as_crispy_field }}
        <p id="error_1_id_username" class="invalid-feedback" style="display: inline-block;"><strong id="gstt"></strong>
     
          
        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
            {{form.password1 | as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.password2 | as_crispy_field }}
          </div>
        </div>
      </fieldset>
      <section class="mt-4 mr-1 ml-1">
        <button class='button is-link' type="submit" id="disbtn1">Sign Up</button>
        <small class="px-4">Already Registered? &nbsp;<a  class="text-red-500" href="{% url 'login' %}">Log In</a></small>
      </section>
      <div class="subtitle pt-2 mt-1"></div>
    </form>
  </div>
  <div class="column">
  	<img src="https://imgur.com/HWEKDy7.png" width="550" height="328">
  </div>

</div>
<!--small acreen-->
<div class="columns w3-hide-large bg-red-50">
  <div class="column">
    <form method="POST" class="signup_form mr-4 ml-4">
      {% csrf_token %}
      <fieldset>
        <h1 class="py-2 text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
          <span class="block xl:inline">Create
          <span class="block text-orange-600 xl:inline">Account</span>
        </h1>
        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
            {{ form.first_name | as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.last_name | as_crispy_field }}
          </div>
        </div>
        {{ form.username| as_crispy_field }}
        <p id="error_1_id_username" class="invalid-feedback" style="display: inline-block;"><strong id="usrerr"></strong>
        </p>
        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
            {{form.password1 | as_crispy_field }}
          </div>
          <div class="form-group col-md-6 mb-0">
            {{ form.password2 | as_crispy_field }}
          </div>
        </div>
      </fieldset>
      <section class="mt-4 mr-1 ml-1">
        <button  class="button is-link" type="submit" id="disbtn1">Sign Up</button>
        <small class="px-2 tag is-success is-light">Already Registered? &nbsp;<a href="{% url 'login' %}">Log In</a></small>
      </section>
      <div class="subtitle pt-2 mt-1"></div>
    </form>
  </div>
  <div class="column">

  </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
  function ValidateEmail(mail) {
    var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    // if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(myForm.emailAddr.value)) 
    if (mail.match(mailformat)) {
      document.getElementById('usrerr').innerText = "";
      document.getElementById('disbtn1').disabled = false;

      return (true)
    }
    document.getElementById('usrerr').innerText = "You have entered an invalid email address!"
    document.getElementById('disbtn1').disabled = true;

    return (false)
  }

  function validate() {
    var data = document.getElementById("id_username").value;
    checkNumberorEmail();

  }
  function phonenumber(inputtxt) {
    var phoneno = /^\d{10}$/;
    if ((inputtxt.match(phoneno))) {
      document.getElementById('usrerr').innerText = "";
      document.getElementById('disbtn1').disabled = false;
      return true;
    }
    else {
      document.getElementById('usrerr').innerText = "enter 10 digit number";
      document.getElementById('disbtn1').disabled = true;

      return false;
    }
  }


  function checkNumberorEmail() {
    var data = document.getElementById("id_username").value;
    if (isNaN(data)) {
      ValidateEmail(data);

    }
    else {
      phonenumber(data);
    }
  }
</script>
<script>
  $(document).on('change',"#id_gst", function(){
    var inputvalues = $(this).val();
    var gstinformat = new RegExp('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$');

    if (gstinformat.test(inputvalues)) {
     return true;
    } else {
        document.getElementById('gstt').innerText = 'Please Enter Valid GSTIN Number';
        $("#id_gst").val('');
        $("#id_gst").focus();
    }

});
</script>
{% endblock body_account %}